### ISSUE TITLE
component: form

### ISSUE THREAD

**Issue by maoberlehner** [avalanchesass/avalanche#106]
```scss
.c-form__label--before,
.c-form__legend {
  .is-required & {
    &:after {
      content: ' *';
    }
  }
}
```
