### ISSUE TITLE
new package: utility_align_self

### ISSUE THREAD

**Issue by maoberlehner** [avalanchesass/avalanche#225]
``` scss
.u-align-self-center {
  align-self: auto;
}
.u-align-self-bottom {
  align-self: flex-end;
}
```
