### ISSUE TITLE
wrong variable in condition for button size l

### ISSUE THREAD

**Issue by maoberlehner** [avalanchesass/avalanche#25]
``` scss
@if $u-button-size-s {
  .button--l {
    padding: $spacing-s $spacing-m;
  }
}
```
